In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from scipy.linalg import null_space

In [2]:
data = pd.read_csv('https://ctlab.itmo.ru/~aloboda/task4.tsv', sep='\t')

data = data.to_numpy()
X = data[:, :-1]
y = data[:, 2]


In [3]:
beta = np.array([1,0.9])
beta

array([1. , 0.9])

In [4]:
A = np.linalg.inv(np.dot(X.T, X)).dot(X.T)
A

array([[ 0.00100688,  0.00088074,  0.0007546 , ..., -0.00113749,
        -0.00126363, -0.00138977],
       [-0.00125051, -0.00084675, -0.00044299, ...,  0.00561337,
         0.00601713,  0.00642089]])

In [5]:
Z = null_space(A)
Z

array([[-1.61504883e-02, -3.37103491e-02, -2.36761429e-02, ...,
         2.14777849e-02,  2.39863364e-02,  2.64948880e-02],
       [-4.40350823e-02, -4.35715502e-02, -4.38364257e-02, ...,
        -4.50283652e-02, -4.50945841e-02, -4.51608030e-02],
       [ 9.97927494e-01, -2.29904365e-03, -2.16959379e-03, ...,
        -1.58706941e-03, -1.55470694e-03, -1.52234448e-03],
       ...,
       [-1.54483199e-03, -1.12167733e-03, -1.36348000e-03, ...,
         9.97548408e-01, -2.51204264e-03, -2.57249331e-03],
       [-1.50965370e-03, -1.04318624e-03, -1.30973908e-03, ...,
        -2.50922682e-03,  9.97424135e-01, -2.64250323e-03],
       [-1.47447541e-03, -9.64695157e-04, -1.25599816e-03, ...,
        -2.56686166e-03, -2.63968741e-03,  9.97287487e-01]])

In [6]:
eta=0.01
y_step = np.linalg.lstsq(A,beta, rcond=None)[0]
for i in range(1000):
  y_step = y_step - eta * Z.dot(np.dot(Z.T, 2*(y_step-y)))

In [8]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=X[:,0],
    y=y,
    marker=dict(color="gold", size=6),
    mode="markers",
    name="Original"
))

fig.add_trace(go.Scatter(
    x=X[:,0],
    y=y_step,
    marker=dict(color="crimson", size=9),
    mode="markers",
    name="Transformed"
))

fig.add_trace(go.Scatter(
    x=X[:,0],
    y=y_star,
    marker=dict(color="red", size=12),
    name="Regression line"
))

fig.update_layout(title=r"$\beta={}.T$".format(beta),
                  xaxis_title="X",
                  yaxis_title="y",
                  width=800,
                  height=650)

fig.show()